version: "3.9"
services:
  caddy:
    build: .
    restart: always
    networks:
      - ingress
    volumes:
      - ./data/data:/data
      - ./data/config:/config
      - ./Caddyfile:/etc/caddy/Caddyfile
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"

networks:
  ingress:
    driver: bridge
    name: ingress
    ipam:
      driver: default
      config:
        - subnet: 172.30.0.1/16