version: '3.9'
services:
  caddy:
    image: caddy:2
    restart: always
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./volume/certs:/certs
      - ./volume/config:/config
      - ./volume/data:/data
      - ./volume/sites:/srv
