services:
  caddy:
    image: caddy:2
    restart: always
    container_name: caddy
    user: 1000:1000
    networks:
      - ingress
    ports:
      - "80:80/tcp"
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./volume/certs:/certs
      - ./volume/config:/config
      - ./volume/data:/data
      - ./volume/sites:/srv

networks:
  ingress:
    driver: bridge
    name: ingress
