services:
  syncthing1:
    image: syncthing/syncthing
    container_name: syncthing1
    hostname: my-syncthing1
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/drive/syncthing/st-sync1:/var/syncthing
    expose:
      - "8384"
    ports:
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart: unless-stopped
    networks:
      - ingress

networks:
  ingress:
    driver: bridge
    name: ingress
