version: "3"
services:
  syncthing:
    image: syncthing/syncthing
    container_name: syncthing
    hostname: my-syncthing
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /syncthing/st-sync:/var/syncthing
    network_mode: host
    restart: unless-stopped
