version: "3"
services:
  syncthing1:
    image: syncthing/syncthing
    container_name: syncthing1
    hostname: my-syncthing1
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/drive/syncthing/st-sync1:/var/syncthing
    ports:
      - "127.0.0.1:8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    restart: unless-stopped

  syncthing2:
    image: syncthing/syncthing
    container_name: syncthing2
    hostname: my-syncthing2
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/drive/syncthing/st-sync2:/var/syncthing
    ports:
      - "127.0.0.1:8385:8384"
      - "22001:22000/tcp"
      - "22001:22000/udp"
      - "21028:21027/udp"
    restart: unless-stopped

  syncthing3:
    image: syncthing/syncthing
    container_name: syncthing3
    hostname: my-syncthing3
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/drive/syncthing/st-sync3:/var/syncthing
    ports:
      - "127.0.0.1:8386:8384"
      - "22002:22000/tcp"
      - "22002:22000/udp"
      - "21029:21027/udp"
    restart: unless-stopped

  syncthing4:
    image: syncthing/syncthing
    container_name: syncthing4
    hostname: my-syncthing4
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /mnt/drive/syncthing/st-sync4:/var/syncthing
    ports:
      - "127.0.0.1:8387:8384"
      - "22003:22000/tcp"
      - "22003:22000/udp"
      - "21030:21027/udp"
    restart: unless-stopped
