name: Update README with Service List

on:
  push:
    paths:
      - '**/docker-compose*.yml'
      - '**/docker-compose*.yaml'
      - '.github/workflows/update-readme.yml'

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install Python dependencies
        run: pip install pyyaml

      - name: Parse Docker Compose Files and Update README
        run: python .github/scripts/update_readme.py

      - name: Commit and Push if README Changed
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add README.md
          git commit -m "docs: add new service to list" || true
          git push
